services:
  db:
    image: mariadb:10.6.4-focal
    # image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    expose:
      - 3306
      - 33060
  front-end:
    image: nginx:latest
    volumes:
      - ./website:/usr/share/nginx/html/
    ports:
      - 8020:80
    restart: always
    depends_on:
      - db
volumes:
  db_data:
